### ISSUE TITLE
4/28 진행상황 보고

### ISSUE THREAD

**Issue by iknoom** [SomaChatbot26/Chatbot26#1]
1. **유저의 가위바위보 점수 관리**

   1. 다음 함수 3개 만들어주시면 될 것 같습니다!
   2. 가위바위보 결과 수정: saveResult(user_id, win_cnt, draw_cnt) // 승수/비긴수를 유지, user_id가 없을 경우 생성
   3. 가위바위보 결과 조회: findResult(user_id)
   4. 가위바위보 결과 초기화: resetResult(user_id)

2. **전체 인터렉션 틀 잡기**

   1. 거의 완성됐습니다.
   2. 졌을 경우 최종 결과 메세지에서 순위를 보여주면 좋을거같아요
   3. [포기하기] 버튼
      1. 가위바위보 결과를 초기화하는 코드를 추가해야합니다.
   4. [천하제일 사내 랭킹 보기] 버튼
      1. [게임 끝내기]는 없애는게 좋을거같아요
      2. 버튼 이름 수정 : `메인 페이지로` -> `메인 메세지로`

3. **/chatbot API 구현 관련(금요일 오후 4시까지)**

   1. 아래 관련 공지 확인

   2. ```
      3. POST /chatbot API 안내
      
      - 해당 API는 평가를 위해 카카오워크 스페이스 "SW마에스트로 미니 프로젝트"의 모든 멤버에게 챗봇 메시지를 보내는 API입니다.
      - 호출 시에는 body 없이 POST로 https://{URL}/chatbot 형태로 보낼 예정입니다. (URL: 팀별로 메일로 전달된 URL입니다.)
      - **운영 측에서는 공정한 심사를 위해 정확한 날짜와 시간대에 해당 API를 호출하여 평가가 진행되도록 만들 예정이오니 챗봇 프로젝트 진행 시에 반드시 구현해주시길 부탁드립니다.**
      - 이에 대한 구현 방법에 대해서는 챗봇 강좌 튜토리얼([강의 링크](https://swmaestro.goorm.io/learn/lecture/26764/%EC%B9%B4%EC%B9%B4%EC%98%A4%EC%9B%8C%ED%81%AC-%EC%B1%97%EB%B4%87-%EB%A7%8C%EB%93%A4%EA%B8%B0-node-js/lesson/1350122/%EC%9C%A0%EC%A0%80%EC%97%90%EA%B2%8C-%EC%84%A4%EB%AC%B8-%EC%A0%84%EC%86%A1-%EA%B5%AC%ED%98%84-3))에서 포함되어 있으므로 참고해 주시길 바랍니다.
      
      해당 API에 대한 테스트를 위해 카카오워크 스페이스 "SW마에스트로 미니 프로젝트"의 모든 멤버에게 메시지를 보내면 혼란이 생길 수 있으니, **반드시 카카오워크의 개인 워크스페이스를 만들어 테스트 해주시길 바랍니다.**
      ```

   3. 예제보면 할 수 있다고 하는데 제 생각엔 아닌거같아요.(예제대로 하면 10명한테밖에 메세지 안갑니다.)

   4. https://docs.kakaoi.ai/kakao_work/webapireference/users/#userslist

**Comment by iknoom** [comment]
그리고 상준님하고 이야기해봤는데 연속 승수로 하면 게임이 너무 금방 끝나서 점수로 변경했습니다
- 이긴 경우: 최종 점수 += 2
- 비긴 경우: 최종 점수 += 1
- 졌을 경우: 게임 종료

**Comment by jujube0** [comment]
3번 chatbot API 구현은 request element인 cursor 랑 limit 이용하시면 될 것 같습니다!
